/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/v1/panel/outputs": {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Get output relay states
		 * @description Returns the current state of all output relays that are either unlocked or overridden. Returns an empty array when the panel has just booted or been reset and no output activity has occurred.
		 */
		get: {
			parameters: {
				query?: never
				header?: never
				path?: never
				cookie?: never
			}
			requestBody?: never
			responses: {
				/** @description Current output states. */
				200: {
					headers: {
						[name: string]: unknown
					}
					content: {
						"application/json": {
							outputs: {
								/** @description Output relay index (0-indexed). */
								output_id: number
								/** @description Whether the output is currently active (unlocked). People can access whatever is controlled by this output. */
								is_unlocked: boolean
								/** @description Whether this output is being held open by the AxTraxNG server, rather than a decision made by the panel. */
								is_overridden: boolean
							}[]
						}
					}
				}
			}
		}
		put?: never
		/**
		 * Control output relays
		 * @description Send manual output operations to the panel. Each operation targets a specific output relay by index and specifies what to do with it.
		 */
		post: {
			parameters: {
				query?: never
				header?: never
				path?: never
				cookie?: never
			}
			requestBody: {
				content: {
					"application/json": {
						operations: {
							/** @description Output relay index (0-indexed). */
							output_id: number
							/**
							 * @description `pulse` -- open momentarily for `duration` seconds, then re-lock. `open` -- open permanently until explicitly closed. `close` -- close and return to default state.
							 * @enum {string}
							 */
							operation: "pulse" | "open" | "close"
							/**
							 * @description Duration in seconds. Used by `pulse` and `open`.
							 * @default 0
							 */
							duration?: number
						}[]
					}
				}
			}
			responses: {
				/** @description The panel acknowledged the command. */
				200: {
					headers: {
						[name: string]: unknown
					}
					content: {
						"application/json": components["schemas"]["SuccessResponse"]
					}
				}
				/** @description The request body is malformed or contains invalid values. */
				400: {
					headers: {
						[name: string]: unknown
					}
					content: {
						"application/json": components["schemas"]["FormatExceptionResponse"]
					}
				}
				/** @description The panel responded with an unexpected packet. */
				500: {
					headers: {
						[name: string]: unknown
					}
					content: {
						"application/json": components["schemas"]["UnexpectedPacketResponse"]
					}
				}
				/** @description The panel rejected the command (NACK). */
				502: {
					headers: {
						[name: string]: unknown
					}
					content: {
						"application/json": components["schemas"]["NackResponse"]
					}
				}
			}
		}
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	"/v1/webhooks": {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * List registered webhooks
		 * @description Returns all registered webhook endpoints.
		 */
		get: {
			parameters: {
				query?: never
				header?: never
				path?: never
				cookie?: never
			}
			requestBody?: never
			responses: {
				/** @description List of webhooks. */
				200: {
					headers: {
						[name: string]: unknown
					}
					content: {
						"application/json": {
							webhooks: {
								/**
								 * Format: uuid
								 * @description Unique webhook identifier.
								 */
								id: string
								/**
								 * Format: uri
								 * @description The URL that will receive POST deliveries.
								 */
								url: string
							}[]
						}
					}
				}
			}
		}
		put?: never
		/**
		 * Register a webhook
		 * @description Register a new URL to receive event deliveries. Each delivery is signed with the provided key using HMAC-SHA256, sent in the `X-Webhook-Signature` header as a hex-encoded digest.
		 */
		post: {
			parameters: {
				query?: never
				header?: never
				path?: never
				cookie?: never
			}
			requestBody: {
				content: {
					"application/json": {
						/**
						 * Format: uri
						 * @description The URL that will receive POST deliveries.
						 */
						url: string
						/** @description Secret key used to compute the HMAC-SHA256 signature. */
						signing_key: string
					}
				}
			}
			responses: {
				/** @description Webhook registered successfully. */
				201: {
					headers: {
						[name: string]: unknown
					}
					content: {
						"application/json": {
							/** @constant */
							ok: true
							webhook: {
								/** Format: uuid */
								id: string
								/** Format: uri */
								url: string
							}
						}
					}
				}
			}
		}
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	"/v1/webhooks/{id}": {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		post?: never
		/**
		 * Remove a webhook
		 * @description Unregister a webhook by its ID. Future events will no longer be delivered to it.
		 */
		delete: {
			parameters: {
				query?: never
				header?: never
				path: {
					/** @description The webhook ID returned at registration time. */
					id: string
				}
				cookie?: never
			}
			requestBody?: never
			responses: {
				/** @description Webhook removed. */
				200: {
					headers: {
						[name: string]: unknown
					}
					content: {
						"application/json": components["schemas"]["SuccessResponse"]
					}
				}
				/** @description No webhook with that ID exists. */
				404: {
					headers: {
						[name: string]: unknown
					}
					content: {
						"application/json": {
							/** @constant */
							ok?: false
							error?: string
						}
					}
				}
			}
		}
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
}
export type webhooks = Record<string, never>
export interface components {
	schemas: {
		WebhookEvent: {
			/** @description Milliseconds since Unix epoch when the event was observed. */
			time: number
			/**
			 * @description The event type.
			 * @enum {string}
			 */
			type: "output.enabled" | "output.disabled"
			data: components["schemas"]["OutputEventData"]
		}
		OutputEventData: {
			/** @description Output relay index (0-indexed). */
			output_id: number
			/** @description Whether this output is being held open by the AxTraxNG server, rather than a decision made by the panel. */
			is_overridden: boolean
		}
		/**
		 * @example {
		 *       "ok": true
		 *     }
		 */
		SuccessResponse: {
			/** @constant */
			ok: true
		}
		/**
		 * @example {
		 *       "ok": false,
		 *       "error": {
		 *         "type": "format_exception",
		 *         "message": "output_id 33 out of range (0-31)"
		 *       }
		 *     }
		 */
		FormatExceptionResponse: {
			/** @constant */
			ok: false
			error: {
				/** @constant */
				type: "format_exception"
				/** @description Human-readable description of what went wrong. */
				message: string
			}
		}
		/**
		 * @example {
		 *       "ok": false,
		 *       "error": {
		 *         "type": "nack",
		 *         "associated_logs": [
		 *           {
		 *             "destination": [
		 *               "log",
		 *               "event"
		 *             ],
		 *             "severity": "Error",
		 *             "message": "01:03:25:450 PrepareNackResponse: You failed to set the ObviousFlag you big dumb idiot"
		 *           }
		 *         ]
		 *       }
		 *     }
		 */
		NackResponse: {
			/** @constant */
			ok: false
			error: {
				/** @constant */
				type: "nack"
				/** @description Log messages the panel sent before the NACK. May be empty if the panel did not send a PrepareNackResponse log. */
				associated_logs: components["schemas"]["LogPacket"][]
			}
		}
		/**
		 * @example {
		 *       "ok": false,
		 *       "error": {
		 *         "type": "unexpected_packet",
		 *         "packet": {
		 *           "direction": "FromPanel",
		 *           "source": "Panel (Dual Addressing, Main Controller)",
		 *           "destination": "Server",
		 *           "transaction_id": "0x03",
		 *           "command_id": 107,
		 *           "command_name": "RequestFirmVer825",
		 *           "event_flag": "Unset",
		 *           "payload": "0a1b2c"
		 *         }
		 *       }
		 *     }
		 */
		UnexpectedPacketResponse: {
			/** @constant */
			ok: false
			error: {
				/** @constant */
				type: "unexpected_packet"
				packet: components["schemas"]["Frame"]
			}
		}
		LogPacket: {
			/** @description Where the panel intended this log to go. */
			destination: ("log" | "event")[]
			/** @enum {string} */
			severity:
				| "Trace"
				| "Debug"
				| "Info"
				| "Warning"
				| "Error"
				| "Fatal"
				| "Disable"
				| "NotAvailable"
			/** @description The raw log message text from the panel. */
			message: string
		}
		Frame: {
			/** @enum {string} */
			direction: "ToPanel" | "FromPanel"
			/** @description Source address (e.g. `"Server"`, `"Panel (Dual Addressing, Main Controller)"`). */
			source: string
			/** @description Destination address. */
			destination: string
			/** @description Transaction ID as hex (e.g. `"0x03"`). */
			transaction_id: string
			/** @description Raw command byte. */
			command_id: number
			/** @description Human-readable command name, or null if unknown. */
			command_name: string | null
			/** @enum {string} */
			event_flag: "Set" | "Unset"
			/** @description Hex-encoded payload bytes. */
			payload: string
		}
	}
	responses: never
	parameters: never
	requestBodies: never
	headers: never
	pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
