/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as ProfileRouteImport } from "./routes/profile"
import { Route as HubRouteImport } from "./routes/hub"
import { Route as DirectoryRouteImport } from "./routes/directory"
import { Route as AuthRouteRouteImport } from "./routes/_auth/route"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as MemberIdRouteImport } from "./routes/member.$id"
import { Route as AuthLoginRouteImport } from "./routes/_auth/login"

const ProfileRoute = ProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: "/hub",
  path: "/hub",
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: "/directory",
  path: "/directory",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const MemberIdRoute = MemberIdRouteImport.update({
  id: "/member/$id",
  path: "/member/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/directory": typeof DirectoryRoute
  "/hub": typeof HubRoute
  "/profile": typeof ProfileRoute
  "/login": typeof AuthLoginRoute
  "/member/$id": typeof MemberIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/directory": typeof DirectoryRoute
  "/hub": typeof HubRoute
  "/profile": typeof ProfileRoute
  "/login": typeof AuthLoginRoute
  "/member/$id": typeof MemberIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_auth": typeof AuthRouteRouteWithChildren
  "/directory": typeof DirectoryRoute
  "/hub": typeof HubRoute
  "/profile": typeof ProfileRoute
  "/_auth/login": typeof AuthLoginRoute
  "/member/$id": typeof MemberIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/directory" | "/hub" | "/profile" | "/login" | "/member/$id"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/directory" | "/hub" | "/profile" | "/login" | "/member/$id"
  id:
    | "__root__"
    | "/"
    | "/_auth"
    | "/directory"
    | "/hub"
    | "/profile"
    | "/_auth/login"
    | "/member/$id"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DirectoryRoute: typeof DirectoryRoute
  HubRoute: typeof HubRoute
  ProfileRoute: typeof ProfileRoute
  MemberIdRoute: typeof MemberIdRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/profile": {
      id: "/profile"
      path: "/profile"
      fullPath: "/profile"
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/hub": {
      id: "/hub"
      path: "/hub"
      fullPath: "/hub"
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/directory": {
      id: "/directory"
      path: "/directory"
      fullPath: "/directory"
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_auth": {
      id: "/_auth"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/member/$id": {
      id: "/member/$id"
      path: "/member/$id"
      fullPath: "/member/$id"
      preLoaderRoute: typeof MemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_auth/login": {
      id: "/_auth/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DirectoryRoute: DirectoryRoute,
  HubRoute: HubRoute,
  ProfileRoute: ProfileRoute,
  MemberIdRoute: MemberIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
