/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/hub_visits": {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * List hub visits
		 * @description Show all visits. Ordered by date ascending. Returns an array. Defaults start_date to today in America/New_York if not specified.
		 */
		get: operations["getHubVisits"]
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	"/hub_visits/{person_id}/{date}": {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Get a hub visit
		 * @description Returns a single visit, or 404 if the person does not have a visit for that day.
		 */
		get: operations["getHubVisit"]
		put?: never
		post?: never
		/**
		 * Delete a hub visit
		 * @description Deletes the visit for the given person and date. Noop if the visit doesn't exist. Always returns 200 as long as person_id exists and date is not malformed. No content.
		 */
		delete: operations["deleteHubVisit"]
		options?: never
		head?: never
		/**
		 * Create or update a hub visit
		 * @description Creates (or updates) a visit on this date. Notes are appended, app data is merged. Returns the updated object.
		 */
		patch: operations["updateHubVisit"]
		trace?: never
	}
	"/profiles": {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Search profiles
		 * @description The endpoint used by the RC Directory. Used to search and filter members of the RC community.
		 */
		get: operations["searchProfiles"]
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	"/profiles/me": {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Get the current user's profile
		 * @description Returns the profile of the authenticated user.
		 */
		get: operations["getMyProfile"]
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	"/profiles/{person_id_or_email}": {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Get a profile
		 * @description Fetch a profile by person ID or email address. If using an email, it must be URL encoded.
		 */
		get: operations["getProfile"]
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	"/batches": {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * List all batches
		 * @description Returns an array of all batches up to and including the current batch, with the most recent batch first. Future batches are not included.
		 */
		get: operations["listBatches"]
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	"/batches/{batch_id}": {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Get a batch
		 * @description Gets info about a specific batch.
		 */
		get: operations["getBatch"]
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	"/locations": {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * Search locations
		 * @description Search location by name and ascii_name.
		 */
		get: operations["searchLocations"]
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
}
export type webhooks = Record<string, never>
export interface components {
	schemas: {
		Location: {
			id?: number
			name?: string
			ascii_name?: string
			short_name?: string | null
			type?: string
		}
		Batch: {
			id: number
			/** @description Full batch name (e.g. "Summer 1, 2023"). */
			name: string
			/** @description Abbreviated batch name (e.g. "S1'23"). */
			short_name?: string
			/** @description Alternative batch name. */
			alt_name?: string
			/** Format: date */
			start_date: string
			/** Format: date */
			end_date: string
		}
		StintBatch: {
			id?: number
			name?: string
			short_name?: string
			alt_name?: string
		}
		Stint: {
			id: number
			/** @enum {string} */
			type:
				| "retreat"
				| "residency"
				| "research_fellowship"
				| "employment"
				| "facilitatorship"
			title?: string | null
			for_half_batch?: boolean
			in_progress?: boolean
			/** Format: date */
			start_date: string
			/** Format: date */
			end_date?: string | null
			batch?: components["schemas"]["StintBatch"]
		}
		Company: {
			id?: number
			name?: string
		}
		HubVisitPerson: {
			id: number
			name: string
		}
		HubVisit: {
			person: components["schemas"]["HubVisitPerson"]
			/** Format: date */
			date: string
			app_data?: {
				[key: string]: unknown
			}
			notes?: string
			/** Format: date-time */
			created_at?: string
			/** Format: date-time */
			updated_at?: string
			created_by_app?: string | null
			updated_by_app?: string | null
		}
		Profile: {
			id: number
			first_name: string
			last_name: string
			name?: string
			name_hl?: string
			email?: string | null
			github?: string | null
			employer_role?: string | null
			twitter?: string | null
			linkedin?: string | null
			personal_site_url?: string | null
			pronouns?: string | null
			unformatted_phone_number?: string | null
			zoom_url?: string | null
			zulip_id?: number | null
			image_path?: string | null
			phone_number?: string | null
			slug?: string | null
			joy_of_computing_username?: string | null
			bio_rendered?: string | null
			bio_match?: boolean | null
			bio_hl?: string | null
			bio_truncated?: string | null
			before_rc_rendered?: string | null
			before_rc_match?: boolean | null
			before_rc_hl?: string | null
			before_rc_truncated?: string | null
			during_rc_rendered?: string | null
			during_rc_match?: boolean | null
			during_rc_hl?: string | null
			during_rc_truncated?: string | null
			interests_rendered?: string | null
			interests_match?: boolean | null
			interests_hl?: string | null
			interests_truncated?: string | null
			employer_info_rendered?: string | null
			employer_info_match?: boolean | null
			employer_info_hl?: string | null
			employer_info_truncated?: string | null
			github_rendered?: string | null
			github_match?: boolean | null
			github_hl?: string | null
			github_truncated?: string | null
			phone_number_rendered?: string | null
			phone_number_match?: boolean | null
			phone_number_hl?: string | null
			phone_number_truncated?: string | null
			email_rendered?: string | null
			email_match?: boolean | null
			email_hl?: string | null
			email_truncated?: string | null
			current_location?: components["schemas"]["Location"] | null
			stints?: components["schemas"]["Stint"][]
			company?: components["schemas"]["Company"] | null
		}
	}
	responses: never
	parameters: never
	requestBodies: never
	headers: never
	pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
	getHubVisits: {
		parameters: {
			query?: {
				/** @description Only show visits on this date. */
				date?: string
				/** @description Inclusive start date. Defaults to today in America/New_York. */
				start_date?: string
				/** @description Inclusive end date. */
				end_date?: string
				/** @description Filter to a specific person. */
				person_id?: number
				/** @description Page number for pagination. */
				page?: number
				/** @description Number of results per page. Max 200. */
				per_page?: number
			}
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description List of hub visits. */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					"application/json": components["schemas"]["HubVisit"][]
				}
			}
			/** @description Missing or invalid access token. */
			401: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	getHubVisit: {
		parameters: {
			query?: never
			header?: never
			path: {
				person_id: number
				date: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description The hub visit. */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					"application/json": components["schemas"]["HubVisit"]
				}
			}
			/** @description No visit found for this person on this date. */
			404: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	deleteHubVisit: {
		parameters: {
			query?: never
			header?: never
			path: {
				person_id: number
				date: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Visit deleted (or did not exist). */
			200: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	updateHubVisit: {
		parameters: {
			query?: never
			header?: never
			path: {
				person_id: number
				date: string
			}
			cookie?: never
		}
		requestBody?: {
			content: {
				"application/json": {
					/** @description If there are existing notes, new notes are appended with two newlines preceding. */
					notes?: string
					/** @description A JSON string stored with the visit. For a new visit it is set directly; for an existing visit it is merged with existing app data. */
					app_data?: string
				}
			}
		}
		responses: {
			/** @description The created or updated hub visit. */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					"application/json": components["schemas"]["HubVisit"]
				}
			}
		}
	}
	searchProfiles: {
		parameters: {
			query?: {
				/** @description Search by name, skills, profile questions. An empty query returns results in descending order by profile creation date. */
				query?: string
				/** @description Filter to people who have a stint for this batch ID. */
				batch_id?: number
				/** @description Filter to people near this location. */
				location_id?: number
				/** @description Filter to people who have a stint of a certain type. */
				role?: "recurser" | "resident" | "facilitator" | "faculty"
				/** @description Narrow the search space. "current" = people currently at RC. "overlap" = people who overlapped with the current user at RC. */
				scope?: "current" | "overlap"
				/** @description Limit the number of results returned. */
				limit?: number
				/** @description Offset the results for pagination. */
				offset?: number
			}
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description List of matching profiles. */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					"application/json": components["schemas"]["Profile"][]
				}
			}
			/** @description Missing or invalid access token. */
			401: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	getMyProfile: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description The current user's profile. */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					"application/json": components["schemas"]["Profile"]
				}
			}
			/** @description Missing or invalid access token. */
			401: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	getProfile: {
		parameters: {
			query?: never
			header?: never
			path: {
				/** @description The person's RC ID (integer) or email address (URL encoded). */
				person_id_or_email: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description The member's profile. */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					"application/json": components["schemas"]["Profile"]
				}
			}
			/** @description Missing or invalid access token. */
			401: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description No member found with that ID or email. */
			404: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	listBatches: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description List of batches. */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					"application/json": components["schemas"]["Batch"][]
				}
			}
			/** @description Missing or invalid access token. */
			401: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	getBatch: {
		parameters: {
			query?: never
			header?: never
			path: {
				batch_id: number
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description The batch. */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					"application/json": components["schemas"]["Batch"]
				}
			}
			/** @description Missing or invalid access token. */
			401: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description No batch found with that ID. */
			404: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	searchLocations: {
		parameters: {
			query?: {
				/** @description Search location by name and ascii_name. */
				query?: string
				/** @description Number of results to return. */
				limit?: number
			}
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description List of matching locations. */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					"application/json": components["schemas"]["Location"][]
				}
			}
			/** @description Missing or invalid access token. */
			401: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
}
